### ISSUE TITLE
playground does not update

### ISSUE THREAD

**Issue by jsimonclark** [OO-LD/playground#1]
The playground interface ([https://oo-ld.github.io/playground/](https://oo-ld.github.io/playground/)) only updates the context and not the body of the properties. 

Steps to recreate:
- Paste the following schema into the OO-LD schema field:

```
{
  "@context": {
    "emmo": "https://w3id.org/emmo#",
    "hasMeasurementUnit": {
      "@id": "emmo:EMMO_bed1d005_b04e_4a90_94cf_02bc678a8569",
      "@type": "@id"
    }
  },
  "title": "PhysicalQuantity",
  "type": "object",
  "properties": {
    "hasMeasurementUnit": {
      "type": "string"
    }
  }
}
```

**Comment by simontaurus** [comment]
Should be fixed with https://github.com/OO-LD/playground/commit/5c5dc23551fbc96ad6358c1ece01b896ea3f45a1 - please confirm

You can now also use direct links to prefilled schema / data, e. g. 

https://oo-ld.github.io/playground/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAAlnhQqAD3FoQaumELKoUCIhQB6OxQDMMACYA6aQHM7psAGIFZTJEAFkqEJEpNSpdAFV4GCMtN0I%2FFABRUNCAeV48KlcARlcABlLGfNKAFipearIATlLeRuqMIl5SgCY8DAA2AHYADjJhxn7GhU0oQQgqQk1UgF9ltlgobAWUEAAFZUFETDkARREyXSTBBVn5wjBObnE2CClIKilYGg0QYLCIxBRGLxRLJEC3baKKBSGDwLwgVZrRTKMAUXgfN5SZA7WF6KRkHhweA3VQMQh4MBgKCIaFkCDVBRkDhkfSoaEiKhIji0YnGP7hSLRBggpKEBHLIA%3D%3D%3D
